import { injectable, inject } from './injector-service';
import AjaxService from './ajax-service';
import AnalyticsService from './analytics-service';
import AppBrowserService from './appbrowser-service';
import AuthService from './auth-service';
import BookmarkService from './bookmark-service';
import CacheService from './cache-service';
import CalendarService from './calendar-service';
import ConfigService from './config-service';
import DashboardService from './dashboard-service';
import DatabaseService from './database-service';
import JiraService from './jira-service';
import MessageService from './message-service';
import ReportService from './report-service';
import ReportConfigService from './reportconfig-service';
import SessionService from './session-service';
import SuggestionService from './suggestion-service';
import TicketService from './ticket-service';
import UserService from './user-service';
import UserGroupService from './usergroups-service';
import UserUtilsService from './userutils-service';
import UtilsService from './utils-service';
import WorklogService from './worklog-service';

export { inject };

export default function injectServices() {
    injectable(AjaxService, "AjaxService", "$ajax");
    injectable(AnalyticsService, "AnalyticsService", "$analytics");
    injectable(AppBrowserService, "AppBrowserService", "$jaBrowserExtn");
    injectable(AuthService, "AuthService", "$auth");
    injectable(BookmarkService, "BookmarkService", "$bookmark");
    injectable(CacheService, "CacheService", "$cache");
    injectable(CalendarService, "CalendarService", "$calendar");
    injectable(ConfigService, "ConfigService", "$config");
    injectable(DashboardService, "DashboardService", "$dashboard");
    injectable(DatabaseService, "DatabaseService", "$db");
    injectable(JiraService, "JiraService", "$jira");
    injectable(MessageService, "MessageService", "$message");
    injectable(ReportService, "ReportService", "$report");
    injectable(ReportConfigService, "ReportConfigService", "$reportConfig");
    injectable(SessionService, "SessionService", "$session");
    injectable(SuggestionService, "SuggestionService", "$suggestion");
    injectable(TicketService, "TicketService", "$ticket");
    injectable(UserService, "UserService", "$user");
    injectable(UserGroupService, "UserGroupService", "$usergroup");
    injectable(UserUtilsService, "UserUtilsService", "$userutils");
    injectable(UtilsService, "UtilsService", "$utils");
    injectable(WorklogService, "WorklogService", "$worklog");
}